// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2026_Peminjaman_backend.Data;

#nullable disable

namespace _2026_Peminjaman_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260215211640_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("_2026_Peminjaman_backend.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 2, 16, 4, 16, 40, 490, DateTimeKind.Local).AddTicks(446),
                            Email = "admin@mail.com",
                            Name = "Admin",
                            Status = "active"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 2, 16, 4, 16, 40, 490, DateTimeKind.Local).AddTicks(461),
                            Email = "budiraharjo@mail.com",
                            Name = "Budi Raharjo",
                            Status = "active"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 2, 16, 4, 16, 40, 490, DateTimeKind.Local).AddTicks(462),
                            Email = "sitiaminah@mail.com",
                            Name = "Siti Aminah",
                            Status = "inactive"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
