// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2026_peminjaman_backend.Data;

#nullable disable

namespace _2026_peminjaman_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260216162652_InitialPeminjamanLengkap")]
    partial class InitialPeminjamanLengkap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("_2026_peminjaman_backend.Models.Peminjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keperluan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaMahasiswa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ruangan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Peminjaman");
                });
#pragma warning restore 612, 618
        }
    }
}
